version: '3'
services:
  go-cqhttp:
    container_name: go-cqhttp
    image: ghcr.io/mrs4s/go-cqhttp:master
    restart: always
    privileged: true
    ports:
      - 5700:5700
      - 9999:8080
    volumes:
      - ./cqhttp-data:/data
    environment:
      - UPDATE=1
      - GOCQWEBUI=1